blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/screenize/screenize/discussions
    about: For general questions or discussions that aren't bug reports or feature requests.
